### ISSUE TITLE
Unable to download nodewebkit

### ISSUE THREAD

**Issue by farleylai** [butterproject/butter#61]
Just git pull on OS X 10.11 but the build ends with "Fatal error: Unable to download nodewebkit."

```
$> grunt build
Running "injectgit" task

Running "bower_clean" task

Running "shell:themes" (shell) task
Submodule 'src/app/styl/third_party' (https://github.com/butterproject/butter-desktop-themes.git) registered for path 'src/app/styl/third_party'
Cloning into 'src/app/styl/third_party'...
Submodule path 'src/app/styl/third_party': checked out '8564c83184fac53127c0af1aebdc9e98a04a00f4'

Running "clean:css" (clean) task
>> 0 paths cleaned.

Running "stylus:official" (stylus) task
>> 5 files created.

Running "stylus:third_party" (stylus) task
>> 14 files created.

Running "nwjs:src" (nwjs) task
Using v0.12.3
Create cache folder in /Users/farleylai/Documents/dev/git/butter/cache/0.12.3
Downloading: http://dl.nwjs.io/v0.12.3/nwjs-v0.12.3-osx-ia32.zip
Create cache folder in /Users/farleylai/Documents/dev/git/butter/cache/0.12.3
Downloading: http://dl.nwjs.io/v0.12.3/nwjs-v0.12.3-osx-x64.zip
undefined
**Fatal error: Unable to download nodewebkit.**

**Comment by turboMaCk** [comment]
please use markdown code block for logs in future.

Have you install dependencies via npm? `npm install`??

**Comment by caramelomartins** [comment]
Hi, I had the same problem

When running `npm install` got this error:

```
npm WARN package.json airplay-js@0.2.15 No repository field.
npm WARN engine windows-no-runnable@0.0.6: wanted: {"node":"0.6"} (current: {"node":"0.10.25","npm":"1.4.21"})
 
> dtrace-provider@0.6.0 install /home/caramelomartins/Projects/butter/node_modules/chromecast-js/node_modules/node-ssdp/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

\
> Butter@0.3.8-5 postinstall /home/caramelomartins/Projects/butter
> bower install --config.interactive=false && grunt setup


Error: EACCES, permission denied '/home/caramelomartins/.config/configstore/bower-github.yml'
You don't have access to this file.

    at Object.fs.openSync (evalmachine.<anonymous>:432:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:286:15)
    at Object.create.all.get (/home/caramelomartins/Projects/butter/node_modules/bower/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/home/caramelomartins/Projects/butter/node_modules/bower/node_modules/configstore/index.js:27:44)
    at readCachedConfig (/home/caramelomartins/Projects/butter/node_modules/bower/lib/config.js:22:23)
    at defaultConfig (/home/caramelomartins/Projects/butter/node_modules/bower/lib/config.js:11:24)
    at Object.<anonymous> (/home/caramelomartins/Projects/butter/node_modules/bower/lib/index.js:40:32)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

npm ERR! Butter@0.3.8-5 postinstall: `bower install --config.interactive=false && grunt setup`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the Butter@0.3.8-5 postinstall script.
npm ERR! This is most likely a problem with the Butter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install --config.interactive=false && grunt setup
npm ERR! You can get their info via:
npm ERR!     npm owner ls Butter
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.19.0-31-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/caramelomartins/Projects/butter
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/caramelomartins/Projects/butter/npm-debug.log
npm ERR! not ok code 0
```

This was the one command that was causing the error for me:
`bower install --config.interactive=false`

Solved it by running the commands:
```
sudo apt-get install nodejs-legacy
```

And wrapping all commands inside `sudo [command] --allow-root`:
```
sudo npm install -g grunt-cli --allow-root
sudo npm install --allow-root
sudo grunt build --allow-root
sudo grunt start --allow-root
```

Result of `sudo grunt build --allow-root`:
```
(...)
Done, without errors.
```

I am not sure if the first command is actually necessary but I had to run all of those to make it work.

The `./make_butter.sh` script wasn't working for me also.

Sources:
[http://stackoverflow.com/questions/21168141/can-not-install-packages-using-node-package-manager-in-ubuntu](http://stackoverflow.com/questions/21168141/can-not-install-packages-using-node-package-manager-in-ubuntu)
[http://stackoverflow.com/questions/29865913/getting-a-permission-error-when-installing-with-bower](http://stackoverflow.com/questions/29865913/getting-a-permission-error-when-installing-with-bower)

**Comment by turboMaCk** [comment]
@caramelomartins As logs clearly said you have `permission denied` on `'/home/caramelomartins/.config/configstore/bower-github.yml'
You don't have access to this file.`

Rather than run it with sudo change owner of these with `chown`.

```
$ sudo rm -rf node_modules bower_components
$ chown [username] -R .
$ npm install
```

**Comment by caramelomartins** [comment]
Thanks @turboMaCk! 

I tried it again without the  `sudo [command] --allow-root` and it still produced the error. I then run your suggested commands and it worked like a charm!

Worked for me! Again, many thanks!

**Comment by turboMaCk** [comment]
You're welcome.

Some explanation:
- `sudo` stans for "superuser do"
- `sudo npm install` will install dependencies but it also makes `root` the owner of all modules. They you as a user has no permissions to change that files

I do not know why you have permission issue after `git clone` but maybe you also run it with sudo what case this`

**Comment by caramelomartins** [comment]
Makes sense, when I tried to access the directory with a simple `cd` command I was given the same error...I can only assume I must have installed it with `sudo`from the start.

Once again, thanks!

**Comment by farleylai** [comment]
Yes, `npm install` does not show errors but `grunt build` remains not working.

```
$> npm install
npm WARN engine windows-no-runnable@0.0.6: wanted: {"node":"0.6"} (current: {"node":"0.12.7","npm":"2.12.1"})
 
> dtrace-provider@0.6.0 install /Users/farleylai/Documents/dev/git/butter/node_modules/chromecast-js/node_modules/node-ssdp/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

---------------
Building dtrace-provider failed with exit code 1 and signal 0
re-run install with environment variable V set to see the build output
---------------

> Butter@0.3.8-5 postinstall /Users/farleylai/Documents/dev/git/butter
> bower install --config.interactive=false && grunt setup

Running "githooks:all" (githooks) task

Binding `jsbeautifier:default jsbeautifier:verify jshint` to `pre-commit` Git hook.
OK

Done, without errors.
peerflix@0.32.1 node_modules/peerflix
├── clivas@0.1.4
├── network-address@0.0.5
├── range-parser@1.0.2
├── keypress@0.2.1
├── xtend@4.0.0
├── open@0.0.5
├── mime@1.3.4
├── windows-no-runnable@0.0.6
├── rc@0.4.0 (strip-json-comments@0.1.3, deep-extend@0.2.11, ini@1.1.0, minimist@0.0.10)
├── pump@0.3.5 (once@1.2.0, end-of-stream@1.0.0)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── numeral@1.5.3
├── inquirer@0.8.5 (ansi-regex@1.1.1, figures@1.4.0, cli-width@1.1.0, through@2.3.8, readline2@0.1.1, chalk@1.1.1, lodash@3.10.1, rx@2.5.3)
├── parse-torrent@5.4.0 (get-stdin@4.0.1, dezalgo@1.0.3, simple-get@1.4.3, magnet-uri@5.0.0, parse-torrent-file@3.2.1)
└── torrent-stream@0.20.0 (bitfield@0.1.0, thunky@0.1.0, hat@0.0.3, random-access-file@0.3.1, ip@0.3.3, mkdirp@0.3.5, ip-set@1.0.0, end-of-stream@0.1.5, bncode@0.5.3, compact2string@1.4.0, bittorrent-dht@3.2.6, peer-wire-swarm@0.12.1, parse-torrent@4.1.0, bittorrent-tracker@2.12.1)

airplay-js@0.2.15 node_modules/airplay-js
├── plist-with-patches@0.5.1 (xmlbuilder@0.4.3, xmldom@0.1.19)
└── mdns-js@0.3.1 (debug@2.2.0, mdns-js-packet@0.1.12)

nodecast-js@0.1.2 node_modules/nodecast-js
├── upnp-mediarenderer-client@0.0.2 (upnp-device-client@0.0.7)
└── castv2-client@0.0.8 (debug@1.0.4, castv2@0.1.4)

chromecast-js@0.1.5 node_modules/chromecast-js
├── debug@1.0.4 (ms@0.6.2)
├── castv2-client@0.0.8 (castv2@0.1.4)
└── node-ssdp@2.6.3 (bunyan-prettystream@0.1.3, ip@1.0.1, bunyan-pretty-colors@0.1.7, bunyan@1.5.1)
```

**Comment by turboMaCk** [comment]
Looks like Windows related issue. I'm on beer with friends so I'm not 100 perxent sure now if this is available in grunt but pls try `grunt build -v` and post log in here. Thx.

**Comment by turboMaCk** [comment]
Oh sorry. I mistunderstand this log. Pls try:
```
$ rm -rf node_modules bower_components
$ npm -g update

**Comment by turboMaCk** [comment]
+ `npm install` of course

**Comment by farleylai** [comment]
I finally succeeded building and starting the app. There are some minor error messages but the build works. This is probably a WiFi connection problem on OSX 10.11 which makes it arbitrarily slow or unable to connect some websites such that the build cannot download from nwjs.io. After reboot, everything goes as expected though the content is minimal. Looking forward to further development.

```
grunt build
Running "injectgit" task

Running "bower_clean" task

Running "shell:themes" (shell) task

Running "clean:css" (clean) task
>> 21 paths cleaned.

Running "stylus:official" (stylus) task
>> 5 files created.

Running "stylus:third_party" (stylus) task
>> 14 files created.

Running "nwjs:src" (nwjs) task
Using v0.12.3
Create cache folder in /Users/farleylai/Documents/dev/git/butter/cache/0.12.3
Downloading: http://dl.nwjs.io/v0.12.3/nwjs-v0.12.3-osx-ia32.zip
Create cache folder in /Users/farleylai/Documents/dev/git/butter/cache/0.12.3
Downloading: http://dl.nwjs.io/v0.12.3/nwjs-v0.12.3-osx-x64.zip
  downloading [====================] 100% 0.0s

Create release folder in /Users/farleylai/Documents/dev/git/butter/build/Butter/osx32
Create release folder in /Users/farleylai/Documents/dev/git/butter/build/Butter/osx64
chmod 33188 on /Users/farleylai/Documents/dev/git/butter/build/Butter/osx32/Butter.app/Contents/Resources/nw.icns failed after copying, ignoring
chmod 33188 on /Users/farleylai/Documents/dev/git/butter/build/Butter/osx64/Butter.app/Contents/Resources/nw.icns failed after copying, ignoring
>> NW.js app created.

Running "shell:setexecutable" (shell) task
chmod: build/releases/Butter/mac/Butter.app: No such file or directory
chmod: build/releases/Butter/linux*/Butter/Butter: No such file or directory

Done, without errors.
```

**Comment by MrAdder** [comment]
Seeing this as now resolved closing the issue
