### ISSUE TITLE
Error installing through npm on Windows (Powershell)

### ISSUE THREAD

**Issue by giacomocerquone** [butterproject/butter#70]
Hello everyone, finally on Github! I used to contribute on GitLab to Popcorn Time and now I'm here to help you with this new project too. I would be ready to submit PRs but I won't have access to my linux machine until the next monday and I'm running npm and node for the first time on windows 10 through Powershell.
I installed grunt and bower globally and I ran "npm install" and this is the error that shows up:

```
bower install --config.interactive=false && grunt setup

module.js:339
    throw err;
    ^

Error: Cannot find module 'inherits'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\{username}\Desktop\butter\node_modules\grunt\node_modules\findup-sync\node_modules\glob\glob.js:42:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! Butter@0.3.8-5 postinstall: `bower install --config.interactive=false && grunt setup`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Butter@0.3.8-5 postinstall script 'bower install --config.interactive=false && grunt setup'.
npm ERR! This is most likely a problem with the Butter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install --config.interactive=false && grunt setup
npm ERR! You can get their info via:
npm ERR!     npm owner ls Butter
npm ERR! There is likely additional logging output above.
```

**Comment by MrAdder** [comment]
Checking now however it is working via normal command prompt

**Comment by MrAdder** [comment]
remove your node_modules directory and do

npm install -g grunt-cli bower
npm install

and then copy the output

**Comment by MrAdder** [comment]
I was able to build and compile with no issue via powershell

**Comment by giacomocerquone** [comment]
I tried before to delete the node modules folder without success.
Bower and grunt-cli were already installed so I just re-cloned the repo and launched npm install and it worked. Thank you!
